name: Publish
on:
  push:
    branches:
      - main

      - master
jobs:
  publish:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Publish package
        run: deno publish --config jsr.json
